#!/usr/bin/env bash
# Copyright (c) 2026 auggie-launch contributors
# Learning and research only. Any other use is at your own risk.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${AUGGIE_LAUNCH_BIN_DIR:-$HOME/.local/bin}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
CONFIG_DIR="${AUGGIE_LAUNCH_CONFIG_DIR:-$XDG_CONFIG_HOME/auggie-launch}"
USER_ENV="$CONFIG_DIR/.env"
EXAMPLE="$ROOT/.env.example"
WRAPPER="$BIN_DIR/auggie-launch"

usage() {
  cat <<'EOF'
Usage: ./install.sh [options]

Install auggie-launch into ~/.local/bin and optionally create a user .env.

Options:
  --bin-dir DIR     Install wrapper here (default: ~/.local/bin)
  --config-dir DIR  Config directory (default: ~/.config/auggie-launch)
  --force-env       Overwrite existing user .env from .env.example
  --no-env          Skip creating user .env
  --link            Symlink package auggie-launch instead of a small wrapper
  -h, --help        Show this help

After install:
  1. Edit ~/.config/auggie-launch/.env
  2. Ensure ~/.local/bin is on PATH
  3. Run: auggie-launch --print "hi"
EOF
}

FORCE_ENV=0
NO_ENV=0
USE_LINK=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bin-dir) BIN_DIR="$2"; shift 2 ;;
    --config-dir) CONFIG_DIR="$2"; USER_ENV="$CONFIG_DIR/.env"; shift 2 ;;
    --force-env) FORCE_ENV=1; shift ;;
    --no-env) NO_ENV=1; shift ;;
    --link) USE_LINK=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

WRAPPER="$BIN_DIR/auggie-launch"
USER_ENV="$CONFIG_DIR/.env"

if [[ ! -f "$ROOT/main.py" ]]; then
  echo "error: main.py not found in $ROOT" >&2
  exit 1
fi

if [[ ! -f "$ROOT/auggie-launch" ]]; then
  echo "error: auggie-launch entrypoint not found in $ROOT" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required" >&2
  exit 1
fi

mkdir -p "$BIN_DIR" "$CONFIG_DIR"
chmod +x "$ROOT/main.py" "$ROOT/auggie-launch"

if [[ "$USE_LINK" -eq 1 ]]; then
  ln -sfn "$ROOT/auggie-launch" "$WRAPPER"
  echo "linked $WRAPPER -> $ROOT/auggie-launch"
else
  cat >"$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by auggie-launch install.sh. Do not put secrets here.
exec python3 "$ROOT/main.py" "\$@"
EOF
  chmod +x "$WRAPPER"
  echo "installed $WRAPPER"
fi

if [[ "$NO_ENV" -eq 0 ]]; then
  if [[ -f "$USER_ENV" && "$FORCE_ENV" -eq 0 ]]; then
    echo "keep existing config: $USER_ENV"
  else
    if [[ ! -f "$EXAMPLE" ]]; then
      echo "warning: missing $EXAMPLE; writing minimal template" >&2
      cat >"$USER_ENV" <<'EOT'
AUGGIE_LAUNCH_BASE_URL=
AUGGIE_LAUNCH_MODEL=
AUGGIE_LAUNCH_API_KEY=
AUGGIE_LAUNCH_INDEXING_MODE=complete
EOT
    else
      cp -f "$EXAMPLE" "$USER_ENV"
    fi
    chmod 600 "$USER_ENV" 2>/dev/null || true
    echo "wrote $USER_ENV  (edit this file — fill in BASE_URL / MODEL / API_KEY)"
  fi
fi

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo
    echo "note: $BIN_DIR is not on PATH. Add to your shell rc, e.g.:"
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
    ;;
esac

if ! command -v auggie >/dev/null 2>&1; then
  echo
  echo "warning: 'auggie' not found on PATH. Install Augment Code CLI first or set AUGGIE_BIN."
fi

echo
echo "Done."
echo "  1) Edit config:  $USER_ENV"
echo "  2) Run:          auggie-launch --print \"hi\""
echo "  3) Proxy only:   auggie-launch --proxy-only"
