"""Local Augment-compatible proxy for the Auggie CLI, backed by CodeGPT Plus."""
from __future__ import annotations

from . import (  # noqa: F401
    cli,
    codegpt,
    config,
    doctor,
    injections,
    models,
    proxy,
    registry,
    server,
    stats,
    transform,
    truncation,
    upstream,
)
from .cli import main
from .config import (  # noqa: F401
    _HERE,
    _MANAGED_ENV_KEYS,
    _MANAGED_ENV_PREFIXES,
    _REQUIRED_KEYS,
    ACTIVE_BASE_URL,
    API_KEYS,
    AUGGIE_BIN,
    BASE_URL_LOCK,
    CODEGPT_HARNESS,
    CODEGPT_ORG_ID,
    CODEGPT_PROVIDER,
    CODEGPT_SESSION_URL,
    CODEGPT_TOKEN,
    DEBUG_DIR,
    FROZEN_KEYS,
    FROZEN_LOCK,
    HISTORY_SUMMARY_ENABLED,
    HISTORY_SUMMARY_MAX_HISTORY_CHARS,
    HISTORY_SUMMARY_MIN_VERSION,
    HISTORY_SUMMARY_TRIGGER_TOKENS,
    INDEXING_MODE,
    IS_CODEGPT,
    LOCAL_TOKEN,
    MODEL_CONTEXT_TOKENS,
    MODEL_CONTEXT_TOKENS_EXPLICIT,
    MODEL_MAX_OUTPUT_TOKENS,
    PORT,
    REASONING_EFFORT,
    REPLY_LANGUAGE,
    REQUIRE_LOCAL_TOKEN,
    SANITIZE_UPSTREAM_PROMPTS,
    STREAM_THINKING,
    TARGET_API_KEY,
    TARGET_BASE_URL,
    TARGET_MODEL,
    UPSTREAM_5XX_FREEZE_SECONDS,
    UPSTREAM_429_FREEZE_SECONDS,
    UPSTREAM_APP_NAME,
    UPSTREAM_BACKOFF_INITIAL_SECONDS,
    UPSTREAM_BACKOFF_MAX_SECONDS,
    UPSTREAM_COOLDOWN_UNTIL,
    UPSTREAM_MAX_RETRY_AFTER_SECONDS,
    UPSTREAM_MIN_INTERVAL_SECONDS,
    UPSTREAM_NEXT_REQUEST_AT,
    UPSTREAM_RETRIES,
    UPSTREAM_THROTTLE_LOCK,
    UPSTREAM_USER_AGENT,
    VERBOSE,
    __version__,
    _candidate_env_paths,
    _is_managed_env_key,
    _parse_dotenv,
    bounded_float,
    bounded_int,
    codex_user_agent,
    codex_version,
    default_upstream_user_agent,
    detect_codegpt,
    env_int,
    env_truthy,
    load_config,
    load_dotenv_files,
    log,
    with_codex_headers,
)
from .injections import build_injected_environment, generate_injected_mcp_config  # noqa: F401
from .models import (  # noqa: F401
    effective_context_limit,
    fetch_upstream_models,
    known_model_names,
    lookup_catalog_context,
    model_context_limit,
    resolve_request_model,
)
from .proxy import (  # noqa: F401
    AuggieProxy,
    augment_chat_response,
    augment_usage,
    estimate_usage,
    extract_chat_text,
    read_json,
)
from .registry import (  # noqa: F401
    fake_batch_upload,
    fake_find_missing,
    fake_generic,
    fake_models,
    fake_token,
    model_list_entry,
)
from .server import (  # noqa: F401
    find_free_port,
    print_env,
    print_models,
    stop_server,
)
from .transform import (  # noqa: F401
    append_current_tool_results,
    append_history_messages,
    build_openai_messages,
    build_openai_request,
    build_openai_tools,
    build_system_prompt,
    current_message_text,
    node_text,
    node_tool_result,
    node_tool_use,
    normalize_schema,
    parse_tool_schema,
    should_use_completion_tokens,
    text_from_value,
)
from .truncation import (  # noqa: F401
    ConversationTurn,
    estimate_message_tokens,
    estimate_tokens_heuristic,
    group_messages_into_turns,
    merge_stream_tool_calls,
    repair_json_arguments,
    tool_calls_to_nodes,
    truncate_messages_to_context_limit,
)
from .upstream import (  # noqa: F401
    _CONNECTION_POOL,
    ConnectionPool,
    UpstreamResponseWrapper,
    active_base_url,
    apply_upstream_cooldown,
    clamp_retry_delay,
    compact_upstream_error,
    get_active_key,
    is_retryable_upstream_status,
    json_bytes,
    log_router_response_headers,
    mark_key_failed,
    open_upstream_with_retries,
    parse_retry_after,
    reset_throttles,
    retry_backoff_seconds,
    upstream_headers,
    upstream_url,
    wait_for_upstream_slot,
)

__all__ = ["__version__", "main"]
